# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8885eb5f616d72a44f130cbb3b0ef78f20bcaf2a9c567bb4bc4a67044d010a9e9e9d7c519b88996fd9e88075779dada7b803da26d2a462c99990968e2de8d4c3

test:
  secret_key_base: 13e3c91686d977b74cd987ae94499c21add7cff026ab98366a3edb344cb25172687d16d4f89bd8c657ba6da2facfb186c8b88c36a2954744846f6171d08cf6ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
